# Generated by Django 5.2.7 on 2025-11-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_userprofile_age_userprofile_comments_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'default_related_name': 'books', 'get_latest_by': 'published_date', 'ordering': ['published_date'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'published_date'], name='idx_book_title_pub_date'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'published_date'), name='unq_title_pub_date'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('pages__gte', 0)), name='book_pages_constraint'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
